// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

contract ChessWager is Ownable {
    using ECDSA for bytes32;
    using MessageHashUtils for bytes32;

    uint256 public constant CREATOR_FEE_PERCENTAGE = 2;
    // Commission wallet — all 2% fees are sent here permanently
    address public constant CREATOR_WALLET = 0x493FEf1Dbd3989A5bb8b467Ef0a787669053F0B5;
    address public backendSigner; // Address of the server that signs the game results

    struct Game {
        address player1;
        address player2;
        uint256 wagerAmount;
        bool isResolved;
    }

    mapping(string => Game) public games;

    event GameCreated(string gameId, address player1, uint256 wagerAmount);
    event GameJoined(string gameId, address player2);
    event GameResolved(string gameId, address winner, uint256 payout, uint256 fee);
    event GameCanceled(string gameId);

    constructor(address _backendSigner) Ownable(msg.sender) {
        backendSigner = _backendSigner;
    }

    function setBackendSigner(address _newSigner) external onlyOwner {
        backendSigner = _newSigner;
    }

    function createGame(string calldata gameId) external payable {
        require(msg.value > 0, "Wager must be greater than 0");
        require(games[gameId].player1 == address(0), "Game already exists");

        games[gameId] = Game({
            player1: msg.sender,
            player2: address(0),
            wagerAmount: msg.value,
            isResolved: false
        });

        emit GameCreated(gameId, msg.sender, msg.value);
    }

    function joinGame(string calldata gameId) external payable {
        Game storage game = games[gameId];
        require(game.player1 != address(0), "Game does not exist");
        require(game.player2 == address(0), "Game already full");
        require(msg.value == game.wagerAmount, "Incorrect wager amount");
        require(msg.sender != game.player1, "Cannot join own game");

        game.player2 = msg.sender;
        emit GameJoined(gameId, msg.sender);
    }

    // signature is generated by the backend
    function resolveGame(
        string calldata gameId,
        address winner,
        bool isDraw,
        bytes calldata signature
    ) external {
        Game storage game = games[gameId];
        require(game.player1 != address(0), "Game does not exist");
        require(game.player2 != address(0), "Game not fully joined");
        require(!game.isResolved, "Game already resolved");
        
        // Recover signer from signature
        // Message format: gameId + winner (or zero address if draw) + isDraw
        bytes32 messageHash = keccak256(abi.encodePacked(gameId, winner, isDraw));
        bytes32 ethSignedMessageHash = messageHash.toEthSignedMessageHash();
        require(ethSignedMessageHash.recover(signature) == backendSigner, "Invalid backend signature");

        game.isResolved = true;

        if (isDraw) {
            // Refund players
            payable(game.player1).transfer(game.wagerAmount);
            payable(game.player2).transfer(game.wagerAmount);
            emit GameResolved(gameId, address(0), 0, 0);
        } else {
            require(winner == game.player1 || winner == game.player2, "Winner not in game");
            
            uint256 totalPot = game.wagerAmount * 2;
            uint256 fee = (totalPot * CREATOR_FEE_PERCENTAGE) / 100;
            uint256 payout = totalPot - fee;

            payable(CREATOR_WALLET).transfer(fee);
            payable(winner).transfer(payout);

            emit GameResolved(gameId, winner, payout, fee);
        }
    }

    // In case player 1 creates but no one joins, they can cancel
    function cancelGame(string calldata gameId) external {
        Game storage game = games[gameId];
        require(game.player1 == msg.sender, "Not player 1");
        require(game.player2 == address(0), "Game already joined");
        require(!game.isResolved, "Game already resolved");

        game.isResolved = true;
        payable(msg.sender).transfer(game.wagerAmount);

        emit GameCanceled(gameId);
    }
}
